map_type: costmap
transform_tolerance: 2.0
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inscribed_radius: 0.25
circumscribed_radius: 0.3
# robot_radius: 0.3
footprint: [ [0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3] ]
inflation_radius: 0.32
cost_scaling_factor: 15.0
lethal_cost_threshold: 100




